source $HOME/AppData/Local/nvim/vim-plug/plugin.vim
source $HOME/AppData/Local/nvim/themes/onedark.vim
source $HOME/AppData/Local/nvim/general/settings.vim
source $HOME/AppData/Local/nvim/keys/mappings.vim
source $HOME/AppData/Local/nvim/plug-config/coc.vim
source $HOME/AppData/Local/nvim/themes/airline.vim
source $HOME/AppData/Local/nvim/plug-config/telescope.vim
source $HOME/AppData/Local/nvim/plug-config/floaterm.vim
lua require'plug-colorizer'
source $HOME/AppData/Local/nvim/plug-config/easymotion.vim
source $HOME/AppData/Local/nvim/plug-config/start-screen.vim
source $HOME/AppData/Local/nvim/plug-config/signify.vim
source $HOME/AppData/Local/nvim/plug-config/rainbow.vim
